<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PC335498" name="com.pearson.tests.TC003_V2SearchTest" tests="166" failures="0" timestamp="27 Dec 2016 08:11:26 GMT" time="585.843" errors="61">
  <testcase name="multiSpecificField_V2Search_GET" time="3.004" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="singleSpecificField_V2Search_POST" time="2.938" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="singleSpecificField_V2Search_GET" time="4.102" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="logicalOperator_ExactPharse_V2Search_GET" time="3.440" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiSpecificField_V2Search_GET" time="4.133" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="1">
      <![CDATA[java.lang.AssertionError: 1
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_GET(TC003_V2SearchTest.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.pearson.regression.utilityHelpers.Template.getMultipleSpecficFieldNames(Template.java:332)
	at com.pearson.pageobjects.V2SearchRequest.getMultipleSpecificFieldWildCard_ResponseValidate(V2SearchRequest.java:132)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_GET(TC003_V2SearchTest.java:70)
	... 24 more
]]>
    </error>
  </testcase> <!-- multiSpecificField_V2Search_GET -->
  <testcase name="logicalOperator_ExactPharse_V2Search_POST" time="1.430" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="Unexpected character (q) at position 3.">
      <![CDATA[java.lang.AssertionError: Unexpected character (q) at position 3.
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.regression.utilityHelpers.ExceptionHandler.logException(ExceptionHandler.java:20)
	at com.pearson.regression.utilityHelpers.Template.convertStringtoJsonObject(Template.java:47)
	at com.pearson.pageobjects.V2SearchRequest.postLogicalOperator_ExactPharse(V2SearchRequest.java:496)
	at com.pearson.tests.TC003_V2SearchTest.logicalOperator_ExactPharse_V2Search_POST(TC003_V2SearchTest.java:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: net.minidev.json.parser.ParseException: Unexpected character (q) at position 3.
	at net.minidev.json.parser.JSONParserBase.readObject(JSONParserBase.java:538)
	at net.minidev.json.parser.JSONParserBase.readFirst(JSONParserBase.java:297)
	at net.minidev.json.parser.JSONParserBase.parse(JSONParserBase.java:154)
	at net.minidev.json.parser.JSONParserString.parse(JSONParserString.java:58)
	at net.minidev.json.parser.JSONParserString.parse(JSONParserString.java:39)
	at net.minidev.json.parser.JSONParser.parse(JSONParser.java:255)
	at com.pearson.regression.utilityHelpers.Template.convertStringtoJsonObject(Template.java:45)
	... 26 more
]]>
    </error>
  </testcase> <!-- logicalOperator_ExactPharse_V2Search_POST -->
  <testcase name="logicalOperator_ExactPharse_V2Search_GET" time="2.873" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiSpecificField_V2Search_POST" time="4.281" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="1">
      <![CDATA[java.lang.AssertionError: 1
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:94)
	at sun.reflect.GeneratedMethodAccessor199.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.pearson.regression.utilityHelpers.Template.getMultipleSpecficFieldNames(Template.java:332)
	at com.pearson.pageobjects.V2SearchRequest.postMultipleSpecificFieldWildCard_ResponseValidate(V2SearchRequest.java:341)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:89)
	... 23 more
]]>
    </error>
  </testcase> <!-- multiSpecificField_V2Search_POST -->
  <testcase name="singleSpecificField_V2Search_POST" time="3.875" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiFieldWithComboLogic_V2Search_GET" time="2.894" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiSpecificField_V2Search_GET" time="4.137" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_GET(TC003_V2SearchTest.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.NullPointerException
	at com.pearson.regression.utilityHelpers.APIHelper.getExpectedFieldValue(APIHelper.java:609)
	at com.pearson.regression.utilityHelpers.CSGHelper.verifyv2SearchSpecificField_SearchQueryString_PresentinJSON(CSGHelper.java:50)
	at com.pearson.pageobjects.V2SearchRequest.getMultipleSpecificFieldWildCard_ResponseValidate(V2SearchRequest.java:134)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_GET(TC003_V2SearchTest.java:70)
	... 24 more
]]>
    </error>
  </testcase> <!-- multiSpecificField_V2Search_GET -->
  <testcase name="multiSpecificField_V2Search_GET" time="3.840" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="1">
      <![CDATA[java.lang.AssertionError: 1
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_GET(TC003_V2SearchTest.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.pearson.regression.utilityHelpers.Template.getMultipleSpecficFieldNames(Template.java:332)
	at com.pearson.pageobjects.V2SearchRequest.getMultipleSpecificFieldWildCard_ResponseValidate(V2SearchRequest.java:132)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_GET(TC003_V2SearchTest.java:70)
	... 24 more
]]>
    </error>
  </testcase> <!-- multiSpecificField_V2Search_GET -->
  <testcase name="singleSpecificField_V2Search_POST" time="2.882" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="singleSpecificField_V2Search_POST" time="4.739" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.pearson.pageobjects.V2SearchRequest.postSpecificFielsAndLogicResponseValidate(V2SearchRequest.java:173)
	at com.pearson.tests.TC003_V2SearchTest.singleSpecificField_V2Search_POST(TC003_V2SearchTest.java:127)
	at sun.reflect.GeneratedMethodAccessor198.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
    </error>
  </testcase> <!-- singleSpecificField_V2Search_POST -->
  <testcase name="singleSpecificField_V2Search_POST" time="5.118" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="singleSpecificField_V2Search_POST" time="2.871" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="singleSpecificField_V2Search_POST" time="5.269" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.pearson.pageobjects.V2SearchRequest.postSpecificFielsAndLogicResponseValidate(V2SearchRequest.java:173)
	at com.pearson.tests.TC003_V2SearchTest.singleSpecificField_V2Search_POST(TC003_V2SearchTest.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
    </error>
  </testcase> <!-- singleSpecificField_V2Search_POST -->
  <testcase name="multiFieldWithComboLogic_V2Search_GET" time="4.322" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiFieldWithComboLogic_V2Search_GET(TC003_V2SearchTest.java:171)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.NullPointerException
	at com.pearson.regression.utilityHelpers.APIHelper.getExpectedFieldValue(APIHelper.java:609)
	at com.pearson.regression.utilityHelpers.CSGHelper.verifyv2SearchMultipleField_SearchQueryString_Logic(CSGHelper.java:349)
	at com.pearson.regression.utilityHelpers.CSGHelper.verifyv2SearchMultiFieldSearchWithCombLogic(CSGHelper.java:419)
	at com.pearson.pageobjects.V2SearchRequest.getMultiFieldSearchWithCombLogic(V2SearchRequest.java:467)
	at com.pearson.tests.TC003_V2SearchTest.multiFieldWithComboLogic_V2Search_GET(TC003_V2SearchTest.java:166)
	... 24 more
]]>
    </error>
  </testcase> <!-- multiFieldWithComboLogic_V2Search_GET -->
  <testcase name="multiFieldWithComboLogic_V2Search_GET" time="4.388" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiFieldWithComboLogic_V2Search_GET(TC003_V2SearchTest.java:171)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.NullPointerException
	at com.pearson.regression.utilityHelpers.APIHelper.getExpectedFieldValue(APIHelper.java:609)
	at com.pearson.regression.utilityHelpers.CSGHelper.verifyv2SearchMultipleField_SearchQueryString_Logic(CSGHelper.java:349)
	at com.pearson.regression.utilityHelpers.CSGHelper.verifyv2SearchMultiFieldSearchWithCombLogic(CSGHelper.java:419)
	at com.pearson.pageobjects.V2SearchRequest.getMultiFieldSearchWithCombLogic(V2SearchRequest.java:467)
	at com.pearson.tests.TC003_V2SearchTest.multiFieldWithComboLogic_V2Search_GET(TC003_V2SearchTest.java:166)
	... 24 more
]]>
    </error>
  </testcase> <!-- multiFieldWithComboLogic_V2Search_GET -->
  <testcase name="multiSpecificField_V2Search_GET" time="2.900" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiFieldWithComboLogic_V2Search_GET" time="2.871" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiFieldWithComboLogic_V2Search_GET(TC003_V2SearchTest.java:171)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.NullPointerException
	at com.pearson.regression.utilityHelpers.CSGHelper.verifyv2SearchMultiFieldSearchWithCombLogic(CSGHelper.java:411)
	at com.pearson.pageobjects.V2SearchRequest.getMultiFieldSearchWithCombLogic(V2SearchRequest.java:467)
	at com.pearson.tests.TC003_V2SearchTest.multiFieldWithComboLogic_V2Search_GET(TC003_V2SearchTest.java:166)
	... 24 more
]]>
    </error>
  </testcase> <!-- multiFieldWithComboLogic_V2Search_GET -->
  <testcase name="multiSpecificField_V2Search_POST" time="4.593" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="1">
      <![CDATA[java.lang.AssertionError: 1
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:94)
	at sun.reflect.GeneratedMethodAccessor199.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.pearson.regression.utilityHelpers.Template.getMultipleSpecficFieldNames(Template.java:332)
	at com.pearson.pageobjects.V2SearchRequest.postMultipleSpecificFieldWildCard_ResponseValidate(V2SearchRequest.java:341)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:89)
	... 23 more
]]>
    </error>
  </testcase> <!-- multiSpecificField_V2Search_POST -->
  <testcase name="multiSpecificField_V2Search_POST" time="2.866" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiSpecificField_V2Search_GET" time="2.977" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiSpecificField_V2Search_POST" time="8.039" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.NullPointerException
	at com.pearson.regression.utilityHelpers.APIHelper.getExpectedFieldValue(APIHelper.java:609)
	at com.pearson.regression.utilityHelpers.CSGHelper.verifyv2SearchSpecificField_SearchQueryString_PresentinJSON(CSGHelper.java:50)
	at com.pearson.pageobjects.V2SearchRequest.postMultipleSpecificFieldWildCard_ResponseValidate(V2SearchRequest.java:345)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:89)
	... 24 more
]]>
    </error>
  </testcase> <!-- multiSpecificField_V2Search_POST -->
  <testcase name="logicalOperator_ExactPharse_V2Search_POST" time="2.964" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="singleSpecificField_V2Search_GET" time="2.863" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="singleSpecificField_V2Search_GET" time="2.977" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="logicalOperator_ExactPharse_V2Search_POST" time="2.875" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="logicalOperator_ExactPharse_V2Search_POST" time="2.886" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiSpecificField_V2Search_POST" time="3.478" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="singleSpecificField_V2Search_GET" time="2.886" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiFieldWithComboLogic_V2Search_GET" time="2.873" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiFieldWithComboLogic_V2Search_GET" time="2.894" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="logicalOperator_ExactPharse_V2Search_POST" time="2.881" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiFieldWithComboLogic_V2Search_GET" time="2.930" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiFieldWithComboLogic_V2Search_GET(TC003_V2SearchTest.java:171)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.NullPointerException
	at com.pearson.regression.utilityHelpers.CSGHelper.verifyv2SearchMultiFieldSearchWithCombLogic(CSGHelper.java:411)
	at com.pearson.pageobjects.V2SearchRequest.getMultiFieldSearchWithCombLogic(V2SearchRequest.java:467)
	at com.pearson.tests.TC003_V2SearchTest.multiFieldWithComboLogic_V2Search_GET(TC003_V2SearchTest.java:166)
	... 24 more
]]>
    </error>
  </testcase> <!-- multiFieldWithComboLogic_V2Search_GET -->
  <testcase name="multiSpecificField_V2Search_GET" time="4.497" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="1">
      <![CDATA[java.lang.AssertionError: 1
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_GET(TC003_V2SearchTest.java:75)
	at sun.reflect.GeneratedMethodAccessor163.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.pearson.regression.utilityHelpers.Template.getMultipleSpecficFieldNames(Template.java:332)
	at com.pearson.pageobjects.V2SearchRequest.getMultipleSpecificFieldWildCard_ResponseValidate(V2SearchRequest.java:132)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_GET(TC003_V2SearchTest.java:70)
	... 23 more
]]>
    </error>
  </testcase> <!-- multiSpecificField_V2Search_GET -->
  <testcase name="logicalOperator_ExactPharse_V2Search_POST" time="2.916" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiSpecificField_V2Search_GET" time="3.865" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_GET(TC003_V2SearchTest.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.NullPointerException
	at com.pearson.regression.utilityHelpers.APIHelper.getExpectedFieldValue(APIHelper.java:609)
	at com.pearson.regression.utilityHelpers.CSGHelper.verifyv2SearchSpecificField_SearchQueryString_PresentinJSON(CSGHelper.java:50)
	at com.pearson.pageobjects.V2SearchRequest.getMultipleSpecificFieldWildCard_ResponseValidate(V2SearchRequest.java:134)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_GET(TC003_V2SearchTest.java:70)
	... 24 more
]]>
    </error>
  </testcase> <!-- multiSpecificField_V2Search_GET -->
  <testcase name="multiSpecificField_V2Search_POST" time="2.872" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="1">
      <![CDATA[java.lang.AssertionError: 1
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:94)
	at sun.reflect.GeneratedMethodAccessor199.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.pearson.regression.utilityHelpers.Template.getMultipleSpecficFieldNames(Template.java:332)
	at com.pearson.pageobjects.V2SearchRequest.postMultipleSpecificFieldWildCard_ResponseValidate(V2SearchRequest.java:341)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:89)
	... 23 more
]]>
    </error>
  </testcase> <!-- multiSpecificField_V2Search_POST -->
  <testcase name="multiSpecificField_V2Search_GET" time="2.868" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="singleSpecificField_V2Search_GET" time="2.868" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="logicalOperator_ExactPharse_V2Search_POST" time="2.929" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="singleSpecificField_V2Search_GET" time="2.868" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiSpecificField_V2Search_GET" time="3.607" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="1">
      <![CDATA[java.lang.AssertionError: 1
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_GET(TC003_V2SearchTest.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.pearson.regression.utilityHelpers.Template.getMultipleSpecficFieldNames(Template.java:332)
	at com.pearson.pageobjects.V2SearchRequest.getMultipleSpecificFieldWildCard_ResponseValidate(V2SearchRequest.java:132)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_GET(TC003_V2SearchTest.java:70)
	... 24 more
]]>
    </error>
  </testcase> <!-- multiSpecificField_V2Search_GET -->
  <testcase name="multiSpecificField_V2Search_POST" time="2.919" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="1">
      <![CDATA[java.lang.AssertionError: 1
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:94)
	at sun.reflect.GeneratedMethodAccessor199.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.pearson.regression.utilityHelpers.Template.getMultipleSpecficFieldNames(Template.java:332)
	at com.pearson.pageobjects.V2SearchRequest.postMultipleSpecificFieldWildCard_ResponseValidate(V2SearchRequest.java:341)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:89)
	... 23 more
]]>
    </error>
  </testcase> <!-- multiSpecificField_V2Search_POST -->
  <testcase name="multiFieldWithComboLogic_V2Search_GET" time="2.861" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiSpecificField_V2Search_POST" time="8.284" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="1">
      <![CDATA[java.lang.AssertionError: 1
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:94)
	at sun.reflect.GeneratedMethodAccessor199.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.pearson.regression.utilityHelpers.Template.getMultipleSpecficFieldNames(Template.java:332)
	at com.pearson.pageobjects.V2SearchRequest.postMultipleSpecificFieldWildCard_ResponseValidate(V2SearchRequest.java:341)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:89)
	... 23 more
]]>
    </error>
  </testcase> <!-- multiSpecificField_V2Search_POST -->
  <testcase name="singleSpecificField_V2Search_POST" time="2.865" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="logicalOperator_ExactPharse_V2Search_POST" time="3.026" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="logicalOperator_ExactPharse_V2Search_POST" time="3.161" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="singleSpecificField_V2Search_POST" time="5.485" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="singleSpecificField_V2Search_POST" time="4.637" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiSpecificField_V2Search_GET" time="2.874" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="1">
      <![CDATA[java.lang.AssertionError: 1
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_GET(TC003_V2SearchTest.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.pearson.regression.utilityHelpers.Template.getMultipleSpecficFieldNames(Template.java:332)
	at com.pearson.pageobjects.V2SearchRequest.getMultipleSpecificFieldWildCard_ResponseValidate(V2SearchRequest.java:132)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_GET(TC003_V2SearchTest.java:70)
	... 24 more
]]>
    </error>
  </testcase> <!-- multiSpecificField_V2Search_GET -->
  <testcase name="multiSpecificField_V2Search_POST" time="3.125" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiSpecificField_V2Search_GET" time="3.969" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiSpecificField_V2Search_POST" time="5.081" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="1">
      <![CDATA[java.lang.AssertionError: 1
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:94)
	at sun.reflect.GeneratedMethodAccessor199.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.pearson.regression.utilityHelpers.Template.getMultipleSpecficFieldNames(Template.java:332)
	at com.pearson.pageobjects.V2SearchRequest.postMultipleSpecificFieldWildCard_ResponseValidate(V2SearchRequest.java:341)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:89)
	... 23 more
]]>
    </error>
  </testcase> <!-- multiSpecificField_V2Search_POST -->
  <testcase name="multiFieldWithComboLogic_V2Search_GET" time="2.849" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="logicalOperator_ExactPharse_V2Search_POST" time="3.164" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="singleSpecificField_V2Search_POST" time="3.887" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiSpecificField_V2Search_GET" time="2.867" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="1">
      <![CDATA[java.lang.AssertionError: 1
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_GET(TC003_V2SearchTest.java:75)
	at sun.reflect.GeneratedMethodAccessor163.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.pearson.regression.utilityHelpers.Template.getMultipleSpecficFieldNames(Template.java:332)
	at com.pearson.pageobjects.V2SearchRequest.getMultipleSpecificFieldWildCard_ResponseValidate(V2SearchRequest.java:132)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_GET(TC003_V2SearchTest.java:70)
	... 23 more
]]>
    </error>
  </testcase> <!-- multiSpecificField_V2Search_GET -->
  <testcase name="singleSpecificField_V2Search_GET" time="2.866" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="singleSpecificField_V2Search_GET" time="2.902" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="singleSpecificField_V2Search_GET" time="2.890" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiFieldWithComboLogic_V2Search_GET" time="2.899" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiFieldWithComboLogic_V2Search_GET(TC003_V2SearchTest.java:171)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.NullPointerException
	at com.pearson.regression.utilityHelpers.APIHelper.getExpectedFieldValue(APIHelper.java:609)
	at com.pearson.regression.utilityHelpers.CSGHelper.verifyv2SearchMultipleField_SearchQueryString_Logic(CSGHelper.java:349)
	at com.pearson.regression.utilityHelpers.CSGHelper.verifyv2SearchMultiFieldSearchWithCombLogic(CSGHelper.java:419)
	at com.pearson.pageobjects.V2SearchRequest.getMultiFieldSearchWithCombLogic(V2SearchRequest.java:467)
	at com.pearson.tests.TC003_V2SearchTest.multiFieldWithComboLogic_V2Search_GET(TC003_V2SearchTest.java:166)
	... 24 more
]]>
    </error>
  </testcase> <!-- multiFieldWithComboLogic_V2Search_GET -->
  <testcase name="multiSpecificField_V2Search_GET" time="3.348" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiSpecificField_V2Search_GET" time="3.901" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="1">
      <![CDATA[java.lang.AssertionError: 1
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_GET(TC003_V2SearchTest.java:75)
	at sun.reflect.GeneratedMethodAccessor163.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.pearson.regression.utilityHelpers.Template.getMultipleSpecficFieldNames(Template.java:332)
	at com.pearson.pageobjects.V2SearchRequest.getMultipleSpecificFieldWildCard_ResponseValidate(V2SearchRequest.java:132)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_GET(TC003_V2SearchTest.java:70)
	... 23 more
]]>
    </error>
  </testcase> <!-- multiSpecificField_V2Search_GET -->
  <testcase name="multiSpecificField_V2Search_POST" time="2.872" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="1">
      <![CDATA[java.lang.AssertionError: 1
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:94)
	at sun.reflect.GeneratedMethodAccessor199.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.pearson.regression.utilityHelpers.Template.getMultipleSpecficFieldNames(Template.java:332)
	at com.pearson.pageobjects.V2SearchRequest.postMultipleSpecificFieldWildCard_ResponseValidate(V2SearchRequest.java:341)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:89)
	... 23 more
]]>
    </error>
  </testcase> <!-- multiSpecificField_V2Search_POST -->
  <testcase name="multiSpecificField_V2Search_GET" time="4.206" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="singleSpecificField_V2Search_GET" time="3.514" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiFieldWithComboLogic_V2Search_GET" time="3.216" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="singleSpecificField_V2Search_POST" time="2.866" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiSpecificField_V2Search_POST" time="2.869" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="1">
      <![CDATA[java.lang.AssertionError: 1
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:94)
	at sun.reflect.GeneratedMethodAccessor199.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.pearson.regression.utilityHelpers.Template.getMultipleSpecficFieldNames(Template.java:332)
	at com.pearson.pageobjects.V2SearchRequest.postMultipleSpecificFieldWildCard_ResponseValidate(V2SearchRequest.java:341)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:89)
	... 23 more
]]>
    </error>
  </testcase> <!-- multiSpecificField_V2Search_POST -->
  <testcase name="logicalOperator_ExactPharse_V2Search_POST" time="1.446" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="Unexpected character (q) at position 3.">
      <![CDATA[java.lang.AssertionError: Unexpected character (q) at position 3.
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.regression.utilityHelpers.ExceptionHandler.logException(ExceptionHandler.java:20)
	at com.pearson.regression.utilityHelpers.Template.convertStringtoJsonObject(Template.java:47)
	at com.pearson.pageobjects.V2SearchRequest.postLogicalOperator_ExactPharse(V2SearchRequest.java:496)
	at com.pearson.tests.TC003_V2SearchTest.logicalOperator_ExactPharse_V2Search_POST(TC003_V2SearchTest.java:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: net.minidev.json.parser.ParseException: Unexpected character (q) at position 3.
	at net.minidev.json.parser.JSONParserBase.readObject(JSONParserBase.java:538)
	at net.minidev.json.parser.JSONParserBase.readFirst(JSONParserBase.java:297)
	at net.minidev.json.parser.JSONParserBase.parse(JSONParserBase.java:154)
	at net.minidev.json.parser.JSONParserString.parse(JSONParserString.java:58)
	at net.minidev.json.parser.JSONParserString.parse(JSONParserString.java:39)
	at net.minidev.json.parser.JSONParser.parse(JSONParser.java:255)
	at com.pearson.regression.utilityHelpers.Template.convertStringtoJsonObject(Template.java:45)
	... 26 more
]]>
    </error>
  </testcase> <!-- logicalOperator_ExactPharse_V2Search_POST -->
  <testcase name="multiFieldWithComboLogic_V2Search_GET" time="2.881" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiSpecificField_V2Search_GET" time="2.917" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="singleSpecificField_V2Search_GET" time="3.189" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="singleSpecificField_V2Search_GET" time="2.867" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="singleSpecificField_V2Search_GET" time="2.872" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="singleSpecificField_V2Search_POST" time="2.879" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="logicalOperator_ExactPharse_V2Search_POST" time="1.445" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="Unexpected character (q) at position 3.">
      <![CDATA[java.lang.AssertionError: Unexpected character (q) at position 3.
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.regression.utilityHelpers.ExceptionHandler.logException(ExceptionHandler.java:20)
	at com.pearson.regression.utilityHelpers.Template.convertStringtoJsonObject(Template.java:47)
	at com.pearson.pageobjects.V2SearchRequest.postLogicalOperator_ExactPharse(V2SearchRequest.java:496)
	at com.pearson.tests.TC003_V2SearchTest.logicalOperator_ExactPharse_V2Search_POST(TC003_V2SearchTest.java:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: net.minidev.json.parser.ParseException: Unexpected character (q) at position 3.
	at net.minidev.json.parser.JSONParserBase.readObject(JSONParserBase.java:538)
	at net.minidev.json.parser.JSONParserBase.readFirst(JSONParserBase.java:297)
	at net.minidev.json.parser.JSONParserBase.parse(JSONParserBase.java:154)
	at net.minidev.json.parser.JSONParserString.parse(JSONParserString.java:58)
	at net.minidev.json.parser.JSONParserString.parse(JSONParserString.java:39)
	at net.minidev.json.parser.JSONParser.parse(JSONParser.java:255)
	at com.pearson.regression.utilityHelpers.Template.convertStringtoJsonObject(Template.java:45)
	... 26 more
]]>
    </error>
  </testcase> <!-- logicalOperator_ExactPharse_V2Search_POST -->
  <testcase name="logicalOperator_ExactPharse_V2Search_POST" time="3.745" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiSpecificField_V2Search_POST" time="3.294" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="1">
      <![CDATA[java.lang.AssertionError: 1
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:94)
	at sun.reflect.GeneratedMethodAccessor199.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.pearson.regression.utilityHelpers.Template.getMultipleSpecficFieldNames(Template.java:332)
	at com.pearson.pageobjects.V2SearchRequest.postMultipleSpecificFieldWildCard_ResponseValidate(V2SearchRequest.java:341)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:89)
	... 23 more
]]>
    </error>
  </testcase> <!-- multiSpecificField_V2Search_POST -->
  <testcase name="singleSpecificField_V2Search_POST" time="3.588" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="singleSpecificField_V2Search_POST" time="2.856" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiFieldWithComboLogic_V2Search_GET" time="2.850" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiFieldWithComboLogic_V2Search_GET(TC003_V2SearchTest.java:171)
	at sun.reflect.GeneratedMethodAccessor203.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.NullPointerException
	at com.pearson.regression.utilityHelpers.CSGHelper.verifyv2SearchMultiFieldSearchWithCombLogic(CSGHelper.java:411)
	at com.pearson.pageobjects.V2SearchRequest.getMultiFieldSearchWithCombLogic(V2SearchRequest.java:467)
	at com.pearson.tests.TC003_V2SearchTest.multiFieldWithComboLogic_V2Search_GET(TC003_V2SearchTest.java:166)
	... 23 more
]]>
    </error>
  </testcase> <!-- multiFieldWithComboLogic_V2Search_GET -->
  <testcase name="singleSpecificField_V2Search_GET" time="4.814" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="logicalOperator_ExactPharse_V2Search_POST" time="1.474" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="Unexpected character (q) at position 3.">
      <![CDATA[java.lang.AssertionError: Unexpected character (q) at position 3.
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.regression.utilityHelpers.ExceptionHandler.logException(ExceptionHandler.java:20)
	at com.pearson.regression.utilityHelpers.Template.convertStringtoJsonObject(Template.java:47)
	at com.pearson.pageobjects.V2SearchRequest.postLogicalOperator_ExactPharse(V2SearchRequest.java:496)
	at com.pearson.tests.TC003_V2SearchTest.logicalOperator_ExactPharse_V2Search_POST(TC003_V2SearchTest.java:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: net.minidev.json.parser.ParseException: Unexpected character (q) at position 3.
	at net.minidev.json.parser.JSONParserBase.readObject(JSONParserBase.java:538)
	at net.minidev.json.parser.JSONParserBase.readFirst(JSONParserBase.java:297)
	at net.minidev.json.parser.JSONParserBase.parse(JSONParserBase.java:154)
	at net.minidev.json.parser.JSONParserString.parse(JSONParserString.java:58)
	at net.minidev.json.parser.JSONParserString.parse(JSONParserString.java:39)
	at net.minidev.json.parser.JSONParser.parse(JSONParser.java:255)
	at com.pearson.regression.utilityHelpers.Template.convertStringtoJsonObject(Template.java:45)
	... 26 more
]]>
    </error>
  </testcase> <!-- logicalOperator_ExactPharse_V2Search_POST -->
  <testcase name="singleSpecificField_V2Search_POST" time="2.920" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="logicalOperator_ExactPharse_V2Search_POST" time="2.909" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiSpecificField_V2Search_POST" time="5.700" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="1">
      <![CDATA[java.lang.AssertionError: 1
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.pearson.regression.utilityHelpers.Template.getMultipleSpecficFieldNames(Template.java:332)
	at com.pearson.pageobjects.V2SearchRequest.postMultipleSpecificFieldWildCard_ResponseValidate(V2SearchRequest.java:341)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:89)
	... 24 more
]]>
    </error>
  </testcase> <!-- multiSpecificField_V2Search_POST -->
  <testcase name="logicalOperator_ExactPharse_V2Search_GET" time="4.417" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="logicalOperator_ExactPharse_V2Search_POST" time="3.782" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiSpecificField_V2Search_POST" time="2.866" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="1">
      <![CDATA[java.lang.AssertionError: 1
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.pearson.regression.utilityHelpers.Template.getMultipleSpecficFieldNames(Template.java:332)
	at com.pearson.pageobjects.V2SearchRequest.postMultipleSpecificFieldWildCard_ResponseValidate(V2SearchRequest.java:341)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:89)
	... 24 more
]]>
    </error>
  </testcase> <!-- multiSpecificField_V2Search_POST -->
  <testcase name="multiFieldWithComboLogic_V2Search_GET" time="4.070" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiFieldWithComboLogic_V2Search_GET(TC003_V2SearchTest.java:171)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.NullPointerException
	at com.pearson.regression.utilityHelpers.CSGHelper.verifyv2SearchMultiFieldSearchWithCombLogic(CSGHelper.java:411)
	at com.pearson.pageobjects.V2SearchRequest.getMultiFieldSearchWithCombLogic(V2SearchRequest.java:467)
	at com.pearson.tests.TC003_V2SearchTest.multiFieldWithComboLogic_V2Search_GET(TC003_V2SearchTest.java:166)
	... 24 more
]]>
    </error>
  </testcase> <!-- multiFieldWithComboLogic_V2Search_GET -->
  <testcase name="multiFieldWithComboLogic_V2Search_GET" time="5.107" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiFieldWithComboLogic_V2Search_GET(TC003_V2SearchTest.java:171)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.NullPointerException
	at com.pearson.regression.utilityHelpers.APIHelper.getExpectedFieldValue(APIHelper.java:609)
	at com.pearson.regression.utilityHelpers.CSGHelper.verifyv2SearchMultipleField_SearchQueryString_Logic(CSGHelper.java:349)
	at com.pearson.regression.utilityHelpers.CSGHelper.verifyv2SearchMultiFieldSearchWithCombLogic(CSGHelper.java:419)
	at com.pearson.pageobjects.V2SearchRequest.getMultiFieldSearchWithCombLogic(V2SearchRequest.java:467)
	at com.pearson.tests.TC003_V2SearchTest.multiFieldWithComboLogic_V2Search_GET(TC003_V2SearchTest.java:166)
	... 24 more
]]>
    </error>
  </testcase> <!-- multiFieldWithComboLogic_V2Search_GET -->
  <testcase name="singleSpecificField_V2Search_GET" time="3.129" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="singleSpecificField_V2Search_POST" time="2.868" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="singleSpecificField_V2Search_POST" time="2.876" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiSpecificField_V2Search_GET" time="2.869" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="1">
      <![CDATA[java.lang.AssertionError: 1
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_GET(TC003_V2SearchTest.java:75)
	at sun.reflect.GeneratedMethodAccessor163.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.pearson.regression.utilityHelpers.Template.getMultipleSpecficFieldNames(Template.java:332)
	at com.pearson.pageobjects.V2SearchRequest.getMultipleSpecificFieldWildCard_ResponseValidate(V2SearchRequest.java:132)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_GET(TC003_V2SearchTest.java:70)
	... 23 more
]]>
    </error>
  </testcase> <!-- multiSpecificField_V2Search_GET -->
  <testcase name="singleSpecificField_V2Search_POST" time="2.869" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiSpecificField_V2Search_GET" time="2.896" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="1">
      <![CDATA[java.lang.AssertionError: 1
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_GET(TC003_V2SearchTest.java:75)
	at sun.reflect.GeneratedMethodAccessor163.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.pearson.regression.utilityHelpers.Template.getMultipleSpecficFieldNames(Template.java:332)
	at com.pearson.pageobjects.V2SearchRequest.getMultipleSpecificFieldWildCard_ResponseValidate(V2SearchRequest.java:132)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_GET(TC003_V2SearchTest.java:70)
	... 23 more
]]>
    </error>
  </testcase> <!-- multiSpecificField_V2Search_GET -->
  <testcase name="multiSpecificField_V2Search_POST" time="2.852" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="1">
      <![CDATA[java.lang.AssertionError: 1
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:94)
	at sun.reflect.GeneratedMethodAccessor199.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.pearson.regression.utilityHelpers.Template.getMultipleSpecficFieldNames(Template.java:332)
	at com.pearson.pageobjects.V2SearchRequest.postMultipleSpecificFieldWildCard_ResponseValidate(V2SearchRequest.java:341)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:89)
	... 23 more
]]>
    </error>
  </testcase> <!-- multiSpecificField_V2Search_POST -->
  <testcase name="logicalOperator_ExactPharse_V2Search_POST" time="2.874" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="singleSpecificField_V2Search_POST" time="2.874" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiSpecificField_V2Search_GET" time="3.523" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="1">
      <![CDATA[java.lang.AssertionError: 1
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_GET(TC003_V2SearchTest.java:75)
	at sun.reflect.GeneratedMethodAccessor163.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.pearson.regression.utilityHelpers.Template.getMultipleSpecficFieldNames(Template.java:332)
	at com.pearson.pageobjects.V2SearchRequest.getMultipleSpecificFieldWildCard_ResponseValidate(V2SearchRequest.java:132)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_GET(TC003_V2SearchTest.java:70)
	... 23 more
]]>
    </error>
  </testcase> <!-- multiSpecificField_V2Search_GET -->
  <testcase name="multiSpecificField_V2Search_GET" time="7.108" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_GET(TC003_V2SearchTest.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.NullPointerException
	at com.pearson.regression.utilityHelpers.APIHelper.getExpectedFieldValue(APIHelper.java:609)
	at com.pearson.regression.utilityHelpers.CSGHelper.verifyv2SearchSpecificField_SearchQueryString_PresentinJSON(CSGHelper.java:50)
	at com.pearson.pageobjects.V2SearchRequest.getMultipleSpecificFieldWildCard_ResponseValidate(V2SearchRequest.java:134)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_GET(TC003_V2SearchTest.java:70)
	... 24 more
]]>
    </error>
  </testcase> <!-- multiSpecificField_V2Search_GET -->
  <testcase name="multiSpecificField_V2Search_POST" time="5.361" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.NullPointerException
	at com.pearson.regression.utilityHelpers.APIHelper.getExpectedFieldValue(APIHelper.java:609)
	at com.pearson.regression.utilityHelpers.CSGHelper.verifyv2SearchSpecificField_SearchQueryString_PresentinJSON(CSGHelper.java:50)
	at com.pearson.pageobjects.V2SearchRequest.postMultipleSpecificFieldWildCard_ResponseValidate(V2SearchRequest.java:345)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:89)
	... 24 more
]]>
    </error>
  </testcase> <!-- multiSpecificField_V2Search_POST -->
  <testcase name="singleSpecificField_V2Search_POST" time="5.961" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="logicalOperator_ExactPharse_V2Search_GET" time="4.573" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="singleSpecificField_V2Search_POST" time="2.874" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="singleSpecificField_V2Search_POST" time="3.182" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiSpecificField_V2Search_GET" time="4.210" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_GET(TC003_V2SearchTest.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.NullPointerException
	at com.pearson.regression.utilityHelpers.APIHelper.getExpectedFieldValue(APIHelper.java:609)
	at com.pearson.regression.utilityHelpers.CSGHelper.verifyv2SearchSpecificField_SearchQueryString_PresentinJSON(CSGHelper.java:50)
	at com.pearson.pageobjects.V2SearchRequest.getMultipleSpecificFieldWildCard_ResponseValidate(V2SearchRequest.java:134)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_GET(TC003_V2SearchTest.java:70)
	... 24 more
]]>
    </error>
  </testcase> <!-- multiSpecificField_V2Search_GET -->
  <testcase name="multiSpecificField_V2Search_POST" time="2.912" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="1">
      <![CDATA[java.lang.AssertionError: 1
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:94)
	at sun.reflect.GeneratedMethodAccessor199.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.pearson.regression.utilityHelpers.Template.getMultipleSpecficFieldNames(Template.java:332)
	at com.pearson.pageobjects.V2SearchRequest.postMultipleSpecificFieldWildCard_ResponseValidate(V2SearchRequest.java:341)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:89)
	... 23 more
]]>
    </error>
  </testcase> <!-- multiSpecificField_V2Search_POST -->
  <testcase name="multiSpecificField_V2Search_POST" time="2.885" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="1">
      <![CDATA[java.lang.AssertionError: 1
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:94)
	at sun.reflect.GeneratedMethodAccessor199.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.pearson.regression.utilityHelpers.Template.getMultipleSpecficFieldNames(Template.java:332)
	at com.pearson.pageobjects.V2SearchRequest.postMultipleSpecificFieldWildCard_ResponseValidate(V2SearchRequest.java:341)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:89)
	... 23 more
]]>
    </error>
  </testcase> <!-- multiSpecificField_V2Search_POST -->
  <testcase name="logicalOperator_ExactPharse_V2Search_GET" time="2.914" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiSpecificField_V2Search_GET" time="4.390" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="1">
      <![CDATA[java.lang.AssertionError: 1
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_GET(TC003_V2SearchTest.java:75)
	at sun.reflect.GeneratedMethodAccessor163.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.pearson.regression.utilityHelpers.Template.getMultipleSpecficFieldNames(Template.java:332)
	at com.pearson.pageobjects.V2SearchRequest.getMultipleSpecificFieldWildCard_ResponseValidate(V2SearchRequest.java:132)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_GET(TC003_V2SearchTest.java:70)
	... 23 more
]]>
    </error>
  </testcase> <!-- multiSpecificField_V2Search_GET -->
  <testcase name="multiSpecificField_V2Search_POST" time="5.112" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiSpecificField_V2Search_POST" time="2.907" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="logicalOperator_ExactPharse_V2Search_POST" time="6.176" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="singleSpecificField_V2Search_POST" time="3.524" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="logicalOperator_ExactPharse_V2Search_POST" time="4.284" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="singleSpecificField_V2Search_POST" time="2.903" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiSpecificField_V2Search_POST" time="5.934" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="1">
      <![CDATA[java.lang.AssertionError: 1
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.pearson.regression.utilityHelpers.Template.getMultipleSpecficFieldNames(Template.java:332)
	at com.pearson.pageobjects.V2SearchRequest.postMultipleSpecificFieldWildCard_ResponseValidate(V2SearchRequest.java:341)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:89)
	... 24 more
]]>
    </error>
  </testcase> <!-- multiSpecificField_V2Search_POST -->
  <testcase name="logicalOperator_ExactPharse_V2Search_GET" time="4.559" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiFieldWithComboLogic_V2Search_GET" time="2.807" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiFieldWithComboLogic_V2Search_GET(TC003_V2SearchTest.java:171)
	at sun.reflect.GeneratedMethodAccessor203.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.NullPointerException
	at com.pearson.regression.utilityHelpers.CSGHelper.verifyv2SearchMultiFieldSearchWithCombLogic(CSGHelper.java:411)
	at com.pearson.pageobjects.V2SearchRequest.getMultiFieldSearchWithCombLogic(V2SearchRequest.java:467)
	at com.pearson.tests.TC003_V2SearchTest.multiFieldWithComboLogic_V2Search_GET(TC003_V2SearchTest.java:166)
	... 23 more
]]>
    </error>
  </testcase> <!-- multiFieldWithComboLogic_V2Search_GET -->
  <testcase name="multiSpecificField_V2Search_GET" time="2.916" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiSpecificField_V2Search_GET" time="2.960" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiSpecificField_V2Search_POST" time="2.934" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="1">
      <![CDATA[java.lang.AssertionError: 1
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:94)
	at sun.reflect.GeneratedMethodAccessor199.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.pearson.regression.utilityHelpers.Template.getMultipleSpecficFieldNames(Template.java:332)
	at com.pearson.pageobjects.V2SearchRequest.postMultipleSpecificFieldWildCard_ResponseValidate(V2SearchRequest.java:341)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:89)
	... 23 more
]]>
    </error>
  </testcase> <!-- multiSpecificField_V2Search_POST -->
  <testcase name="logicalOperator_ExactPharse_V2Search_POST" time="1.444" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="Unexpected character (q) at position 3.">
      <![CDATA[java.lang.AssertionError: Unexpected character (q) at position 3.
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.regression.utilityHelpers.ExceptionHandler.logException(ExceptionHandler.java:20)
	at com.pearson.regression.utilityHelpers.Template.convertStringtoJsonObject(Template.java:47)
	at com.pearson.pageobjects.V2SearchRequest.postLogicalOperator_ExactPharse(V2SearchRequest.java:496)
	at com.pearson.tests.TC003_V2SearchTest.logicalOperator_ExactPharse_V2Search_POST(TC003_V2SearchTest.java:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: net.minidev.json.parser.ParseException: Unexpected character (q) at position 3.
	at net.minidev.json.parser.JSONParserBase.readObject(JSONParserBase.java:538)
	at net.minidev.json.parser.JSONParserBase.readFirst(JSONParserBase.java:297)
	at net.minidev.json.parser.JSONParserBase.parse(JSONParserBase.java:154)
	at net.minidev.json.parser.JSONParserString.parse(JSONParserString.java:58)
	at net.minidev.json.parser.JSONParserString.parse(JSONParserString.java:39)
	at net.minidev.json.parser.JSONParser.parse(JSONParser.java:255)
	at com.pearson.regression.utilityHelpers.Template.convertStringtoJsonObject(Template.java:45)
	... 26 more
]]>
    </error>
  </testcase> <!-- logicalOperator_ExactPharse_V2Search_POST -->
  <testcase name="multiSpecificField_V2Search_GET" time="2.960" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiSpecificField_V2Search_POST" time="5.283" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="1">
      <![CDATA[java.lang.AssertionError: 1
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.pearson.regression.utilityHelpers.Template.getMultipleSpecficFieldNames(Template.java:332)
	at com.pearson.pageobjects.V2SearchRequest.postMultipleSpecificFieldWildCard_ResponseValidate(V2SearchRequest.java:341)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:89)
	... 24 more
]]>
    </error>
  </testcase> <!-- multiSpecificField_V2Search_POST -->
  <testcase name="logicalOperator_ExactPharse_V2Search_POST" time="3.026" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="singleSpecificField_V2Search_POST" time="2.868" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="logicalOperator_ExactPharse_V2Search_POST" time="1.453" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="Unexpected character (q) at position 3.">
      <![CDATA[java.lang.AssertionError: Unexpected character (q) at position 3.
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.regression.utilityHelpers.ExceptionHandler.logException(ExceptionHandler.java:20)
	at com.pearson.regression.utilityHelpers.Template.convertStringtoJsonObject(Template.java:47)
	at com.pearson.pageobjects.V2SearchRequest.postLogicalOperator_ExactPharse(V2SearchRequest.java:496)
	at com.pearson.tests.TC003_V2SearchTest.logicalOperator_ExactPharse_V2Search_POST(TC003_V2SearchTest.java:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: net.minidev.json.parser.ParseException: Unexpected character (q) at position 3.
	at net.minidev.json.parser.JSONParserBase.readObject(JSONParserBase.java:538)
	at net.minidev.json.parser.JSONParserBase.readFirst(JSONParserBase.java:297)
	at net.minidev.json.parser.JSONParserBase.parse(JSONParserBase.java:154)
	at net.minidev.json.parser.JSONParserString.parse(JSONParserString.java:58)
	at net.minidev.json.parser.JSONParserString.parse(JSONParserString.java:39)
	at net.minidev.json.parser.JSONParser.parse(JSONParser.java:255)
	at com.pearson.regression.utilityHelpers.Template.convertStringtoJsonObject(Template.java:45)
	... 26 more
]]>
    </error>
  </testcase> <!-- logicalOperator_ExactPharse_V2Search_POST -->
  <testcase name="singleSpecificField_V2Search_POST" time="2.838" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="singleSpecificField_V2Search_POST" time="3.243" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="singleSpecificField_V2Search_POST" time="2.877" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="logicalOperator_ExactPharse_V2Search_POST" time="2.962" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiSpecificField_V2Search_POST" time="4.679" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="1">
      <![CDATA[java.lang.AssertionError: 1
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:94)
	at sun.reflect.GeneratedMethodAccessor199.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.pearson.regression.utilityHelpers.Template.getMultipleSpecficFieldNames(Template.java:332)
	at com.pearson.pageobjects.V2SearchRequest.postMultipleSpecificFieldWildCard_ResponseValidate(V2SearchRequest.java:341)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:89)
	... 23 more
]]>
    </error>
  </testcase> <!-- multiSpecificField_V2Search_POST -->
  <testcase name="singleSpecificField_V2Search_POST" time="3.214" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiSpecificField_V2Search_GET" time="2.871" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="1">
      <![CDATA[java.lang.AssertionError: 1
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_GET(TC003_V2SearchTest.java:75)
	at sun.reflect.GeneratedMethodAccessor163.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.pearson.regression.utilityHelpers.Template.getMultipleSpecficFieldNames(Template.java:332)
	at com.pearson.pageobjects.V2SearchRequest.getMultipleSpecificFieldWildCard_ResponseValidate(V2SearchRequest.java:132)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_GET(TC003_V2SearchTest.java:70)
	... 23 more
]]>
    </error>
  </testcase> <!-- multiSpecificField_V2Search_GET -->
  <testcase name="multiSpecificField_V2Search_GET" time="3.920" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_GET(TC003_V2SearchTest.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.NullPointerException
	at com.pearson.regression.utilityHelpers.APIHelper.getExpectedFieldValue(APIHelper.java:609)
	at com.pearson.regression.utilityHelpers.CSGHelper.verifyv2SearchSpecificField_SearchQueryString_PresentinJSON(CSGHelper.java:50)
	at com.pearson.pageobjects.V2SearchRequest.getMultipleSpecificFieldWildCard_ResponseValidate(V2SearchRequest.java:134)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_GET(TC003_V2SearchTest.java:70)
	... 24 more
]]>
    </error>
  </testcase> <!-- multiSpecificField_V2Search_GET -->
  <testcase name="multiSpecificField_V2Search_POST" time="5.557" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiSpecificField_V2Search_POST" time="4.449" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="1">
      <![CDATA[java.lang.AssertionError: 1
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:94)
	at sun.reflect.GeneratedMethodAccessor199.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.pearson.regression.utilityHelpers.Template.getMultipleSpecficFieldNames(Template.java:332)
	at com.pearson.pageobjects.V2SearchRequest.postMultipleSpecificFieldWildCard_ResponseValidate(V2SearchRequest.java:341)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:89)
	... 23 more
]]>
    </error>
  </testcase> <!-- multiSpecificField_V2Search_POST -->
  <testcase name="multiSpecificField_V2Search_POST" time="2.890" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="logicalOperator_ExactPharse_V2Search_POST" time="5.218" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="singleSpecificField_V2Search_POST" time="5.740" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="singleSpecificField_V2Search_POST" time="3.265" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiSpecificField_V2Search_POST" time="3.504" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="1">
      <![CDATA[java.lang.AssertionError: 1
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:94)
	at sun.reflect.GeneratedMethodAccessor199.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.pearson.regression.utilityHelpers.Template.getMultipleSpecficFieldNames(Template.java:332)
	at com.pearson.pageobjects.V2SearchRequest.postMultipleSpecificFieldWildCard_ResponseValidate(V2SearchRequest.java:341)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:89)
	... 23 more
]]>
    </error>
  </testcase> <!-- multiSpecificField_V2Search_POST -->
  <testcase name="multiSpecificField_V2Search_GET" time="4.230" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiSpecificField_V2Search_POST" time="2.839" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiSpecificField_V2Search_POST" time="6.028" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiSpecificField_V2Search_POST" time="3.163" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="1">
      <![CDATA[java.lang.AssertionError: 1
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:94)
	at sun.reflect.GeneratedMethodAccessor199.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.pearson.regression.utilityHelpers.Template.getMultipleSpecficFieldNames(Template.java:332)
	at com.pearson.pageobjects.V2SearchRequest.postMultipleSpecificFieldWildCard_ResponseValidate(V2SearchRequest.java:341)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:89)
	... 23 more
]]>
    </error>
  </testcase> <!-- multiSpecificField_V2Search_POST -->
  <testcase name="singleSpecificField_V2Search_GET" time="2.865" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiSpecificField_V2Search_POST" time="2.825" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="1">
      <![CDATA[java.lang.AssertionError: 1
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:94)
	at sun.reflect.GeneratedMethodAccessor199.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.pearson.regression.utilityHelpers.Template.getMultipleSpecficFieldNames(Template.java:332)
	at com.pearson.pageobjects.V2SearchRequest.postMultipleSpecificFieldWildCard_ResponseValidate(V2SearchRequest.java:341)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:89)
	... 23 more
]]>
    </error>
  </testcase> <!-- multiSpecificField_V2Search_POST -->
  <testcase name="singleSpecificField_V2Search_POST" time="5.594" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="singleSpecificField_V2Search_GET" time="2.881" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="singleSpecificField_V2Search_POST" time="2.871" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="singleSpecificField_V2Search_GET" time="2.809" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiSpecificField_V2Search_POST" time="5.179" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.NullPointerException
	at com.pearson.regression.utilityHelpers.APIHelper.getExpectedFieldValue(APIHelper.java:609)
	at com.pearson.regression.utilityHelpers.CSGHelper.verifyv2SearchSpecificField_SearchQueryString_PresentinJSON(CSGHelper.java:50)
	at com.pearson.pageobjects.V2SearchRequest.postMultipleSpecificFieldWildCard_ResponseValidate(V2SearchRequest.java:345)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_POST(TC003_V2SearchTest.java:89)
	... 24 more
]]>
    </error>
  </testcase> <!-- multiSpecificField_V2Search_POST -->
  <testcase name="multiFieldWithComboLogic_V2Search_GET" time="2.897" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiFieldWithComboLogic_V2Search_GET(TC003_V2SearchTest.java:171)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.NullPointerException
	at com.pearson.regression.utilityHelpers.CSGHelper.verifyv2SearchMultiFieldSearchWithCombLogic(CSGHelper.java:411)
	at com.pearson.pageobjects.V2SearchRequest.getMultiFieldSearchWithCombLogic(V2SearchRequest.java:467)
	at com.pearson.tests.TC003_V2SearchTest.multiFieldWithComboLogic_V2Search_GET(TC003_V2SearchTest.java:166)
	... 24 more
]]>
    </error>
  </testcase> <!-- multiFieldWithComboLogic_V2Search_GET -->
  <testcase name="multiFieldWithComboLogic_V2Search_GET" time="3.129" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="multiSpecificField_V2Search_GET" time="4.580" classname="com.pearson.tests.TC003_V2SearchTest">
    <error type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_GET(TC003_V2SearchTest.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.NullPointerException
	at com.pearson.regression.utilityHelpers.APIHelper.getExpectedFieldValue(APIHelper.java:609)
	at com.pearson.regression.utilityHelpers.CSGHelper.verifyv2SearchSpecificField_SearchQueryString_PresentinJSON(CSGHelper.java:50)
	at com.pearson.pageobjects.V2SearchRequest.getMultipleSpecificFieldWildCard_ResponseValidate(V2SearchRequest.java:134)
	at com.pearson.tests.TC003_V2SearchTest.multiSpecificField_V2Search_GET(TC003_V2SearchTest.java:70)
	... 24 more
]]>
    </error>
  </testcase> <!-- multiSpecificField_V2Search_GET -->
  <testcase name="singleSpecificField_V2Search_POST" time="2.867" classname="com.pearson.tests.TC003_V2SearchTest"/>
  <testcase name="singleSpecificField_V2Search_POST" time="2.939" classname="com.pearson.tests.TC003_V2SearchTest"/>
</testsuite> <!-- com.pearson.tests.TC003_V2SearchTest -->
